# Change these first
owner: soneji # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Chrome
    url: $chrome
  - name: CTF
    url: https://piratecloud.tk
  - name: Droppy
    url: $droppy
  - name: Firefox
    url: $firefox
  - name: GitHub
    url: https://github.soneji.xyz
  - name: Images
    url: $images
  - name: Javamail
    url: $javamail
  - name: mama
    url: $mama
  - name: Minecraft
    url: $minecraft
  - name: NextCloud
    url: $nextcloud
  - name: OnlyOffice (for NextCloud)
    url: $onlyoffice
  - name: Plex
    url: $plex
  - name: QB
    url: $qb
  - name: Family Shop
    url: https://$family_shop
  - name: Family Shop (Shop)
    url: https://shop.$family_shop
  - name: Family Shop (Online)
    url: https://online.$family_shop
  - name: Shynet Analytics
    url: https://shynetanalytics.com
  - name: Sizzy
    url: $sizzy
  - name: soneji.xyz
    url: soneji.xyz
  - name: dhavalsoneji.com
    url: dhavalsoneji.com
  - name: Spotify Vibe Check
    url: spotify-vibe-check.soneji.xyz
  - name: VHM
    url: $vhm
  - name: Venom
    url: $venom
  - name: VSCode
    url: $vscode
    

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: uptime.soneji.xyz
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /uptime
  logoUrl: https://avatars3.githubusercontent.com/u/12625848
  name: "Dhaval's Upptime"
  #introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  #introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Home
      href: https://soneji.xyz
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
